### ISSUE TITLE
RpcRouter Delayed Stream Value Propagation

### ISSUE THREAD

**Issue by sukazavr** [Effect-TS/effect#3702]
### What version of Effect is running?

3.8.3

### What steps can reproduce the bug?

1. Set up an RpcRouter with Rpc.stream.
2. Create a stream that emits multiple values at different intervals.
3. Observe the timing of value propagation to the client.

Here is the reproduction of the bug: https://stackblitz.com/edit/vitejs-vite-rqzpfs?file=src%2Fserver%2Frouter.ts

### What is the expected behavior?

- Each value emitted by the stream should be instantly propagated to the client.
- The timing between value emissions should match the intervals set in the stream.

### What do you see instead?

- The first value is emitted instantly as expected.
- Subsequent values are delayed:
- - The second value, expected 1 second after the first, is emitted 2 seconds later.
- - The third and fourth values are emitted together, not respecting their intended intervals.
- Values seem to wait for the next emission or the end of the stream before being propagated.

**Comment by mikearnaldi** [comment]
clearly you can't get exactly the same delays as there is network in between

**Comment by mikearnaldi** [comment]
That said the behaviour is odd indeed

**Comment by tim-smart** [comment]
A websocket transport is planned which should solve this.

Currently streaming is done using a plain http stream, which will be likely hitting some layers of buffering.

**Comment by mikearnaldi** [comment]
I changed the timeouts to be way higher and still see odd behavior, doesn't look like a buffering issue
